In [2]:
!pip3 install torch torchvision torchaudio

  Using cached numpy-2.1.3-cp310-cp310-macosx_14_0_arm64.whl.metadata (62 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.9/63.9 MB 3.8 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 3.8 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 3.6 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 3.7 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 3.9 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 3.9 MB/s eta 0:00:00a 0:00:01
Using cached numpy-2.1.3-cp310-cp310-macosx_14_0_arm64.whl (5.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 5.9 MB/s eta 0:00:00


In [4]:
%time

import torch
import numpy as np

CPU times: user 3 μs, sys: 1 μs, total: 4 μs
Wall time: 5.25 μs


In [5]:
data = [[1, 2], [2, 3]]
x_data = torch.tensor(data)

In [17]:
x_data

tensor([[1, 2],
        [2, 3]])

In [18]:
numpy_data = np.array(data)
numpy_data

array([[1, 2],
       [2, 3]])

In [24]:
x_np = torch.from_numpy(numpy_data)

In [25]:
x_np

tensor([[1, 2],
        [2, 3]])

In [26]:
x_ones = torch.ones_like(x_data)

In [28]:
x_ones

tensor([[1, 1],
        [1, 1]])

In [31]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
x_rand

tensor([[0.5050, 0.2884],
        [0.0334, 0.1305]])

In [32]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.8546, 0.2133, 0.9643],
        [0.0422, 0.8336, 0.5480]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [33]:
rand_tensor.shape, rand_tensor.dtype, rand_tensor.device

(torch.Size([2, 3]), torch.float32, device(type='cpu'))

In [36]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[:,-1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [37]:
t1 = torch.concat([tensor, tensor, tensor], dim=1)
t1

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

In [38]:
y1= tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

In [39]:
y1, y2

(tensor([[3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.]]),
 tensor([[3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.]]))

In [41]:
y3 = torch.rand_like(y1)
y3

tensor([[0.9207, 0.2842, 0.1652, 0.6037],
        [0.5468, 0.6660, 0.1083, 0.4819],
        [0.9971, 0.2278, 0.2853, 0.6720],
        [0.6403, 0.4934, 0.6942, 0.1955]])

In [42]:
torch.matmul(tensor, tensor.T, out=y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [43]:
y3

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [44]:
z1 = tensor * tensor
z1

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [45]:
z2 = torch.mul(tensor, tensor)
z2

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [50]:
z3 = torch.rand_like(z2)
z3

tensor([[0.1440, 0.1357, 0.1500, 0.0162],
        [0.1760, 0.6615, 0.4147, 0.6521],
        [0.3478, 0.6716, 0.6700, 0.5022],
        [0.0620, 0.0022, 0.2370, 0.3092]])

In [52]:
torch.mul(tensor, z3, out=y3)

tensor([[0.1440, 0.0000, 0.1500, 0.0162],
        [0.1760, 0.0000, 0.4147, 0.6521],
        [0.3478, 0.0000, 0.6700, 0.5022],
        [0.0620, 0.0000, 0.2370, 0.3092]])

In [54]:
agg = tensor.sum()
agg.item(), type(agg)

(12.0, torch.Tensor)

In [55]:
tensor.add_(5)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

In [56]:
tensor

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

In [58]:
t1 = torch.ones(5)

t2 = t1.numpy()

t1, t2

(tensor([1., 1., 1., 1., 1.]), array([1., 1., 1., 1., 1.], dtype=float32))

In [59]:
t1.add_(4)

tensor([5., 5., 5., 5., 5.])

In [60]:
t1, t2

(tensor([5., 5., 5., 5., 5.]), array([5., 5., 5., 5., 5.], dtype=float32))

In [66]:
n1 = np.ones(5)

n2 = torch.from_numpy(n1)

In [67]:
n2, n1

(tensor([1., 1., 1., 1., 1.], dtype=torch.float64),
 array([1., 1., 1., 1., 1.]))

In [68]:
np.add(n1, 1, out=n1)

array([2., 2., 2., 2., 2.])

In [69]:
n2

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

## Future Ref

[Datasets & DataLoaders](https://pytorch.org/tutorials/beginner/basics/data_tutorial.html)